// File generated by flutterfire_cli.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc4v_CqP_YyUYgBLxer-UmrteGXG0OrEI',
    appId: '1:735490202400:web:73001863b8a216d6a75545',
    messagingSenderId: '735490202400',
    projectId: 'ethyf-3b21f',
    authDomain: 'ethyf-3b21f.firebaseapp.com',
    databaseURL: 'https://ethyf-3b21f.firebaseio.com',
    storageBucket: 'ethyf-3b21f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc4v_CqP_YyUYgBLxer-UmrteGXG0OrEI',
    appId: '1:735490202400:web:73001863b8a216d6a75545',
    messagingSenderId: '735490202400',
    projectId: 'ethyf-3b21f',
    databaseURL: 'https://ethyf-3b21f.firebaseio.com',
    storageBucket: 'ethyf-3b21f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc4v_CqP_YyUYgBLxer-UmrteGXG0OrEI',
    appId: '1:735490202400:web:73001863b8a216d6a75545',
    messagingSenderId: '735490202400',
    projectId: 'ethyf-3b21f',
    databaseURL: 'https://ethyf-3b21f.firebaseio.com',
    storageBucket: 'ethyf-3b21f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc4v_CqP_YyUYgBLxer-UmrteGXG0OrEI',
    appId: '1:735490202400:web:73001863b8a216d6a75545',
    messagingSenderId: '735490202400',
    projectId: 'ethyf-3b21f',
    databaseURL: 'https://ethyf-3b21f.firebaseio.com',
    storageBucket: 'ethyf-3b21f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc4v_CqP_YyUYgBLxer-UmrteGXG0OrEI',
    appId: '1:735490202400:web:73001863b8a216d6a75545',
    messagingSenderId: '735490202400',
    projectId: 'ethyf-3b21f',
    databaseURL: 'https://ethyf-3b21f.firebaseio.com',
    storageBucket: 'ethyf-3b21f.firebasestorage.app',
  );
}
